server:
  port: 9092
  servlet:
    context-path: /
spring:
  datasource:
    password: 660708
    username: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.103/employee

